version: "3"
services:
  nexus3:
    image: sonatype/nexus3:3.41.0
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
    driver: local
